# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Finite"
license = "MIT"
licenselink = "https://github.com/lambdafu.net/hugo-finite/blob/master/LICENSE.md"
description = "A simple academic theme."
homepage = "https://github.com/lambdafu/hugo-finite"
tags = ["academic", "basic"]
features = ["posts", "publications", "social"]
min_version = 0.15

[author]
  name = "Marcus Brinkmann"
  homepage = "https://lambdafu.net/"

